name: deploy

on:
  push:
    branches:
      - main
    paths:
      # When we update the Flutter version, we want to trigger a new build.
      - ".fvm/fvm_config.json"
      # When we update the Firebase configuration (like a new redirect), we want
      # to trigger a new build.
      - "firebase.json"
      # We only build and deploy a new version, when a user relevant files
      # changed.
      - "lib/**"
      - "pubspec.yaml"
      # We trigger also this workflow, if this workflow is changed, so that new
      # changes will be applied.
      - ".github/workflows/deploy.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # We only want to run one deploy job at a time.
  group: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Flutter version from FVM config file to environment variables
      uses: kuhnroyal/flutter-fvm-config-action@v1
    
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}
    
    - name: Build
      run: |
        # We disable the PWA because it makes no sense for a landing page.
        flutter build web \
          --pwa-strategy=none
    
    - name: Deploy
      env:
        SHAREZONE_PROD_KEY: ${{ secrets.FIREBASE_HOSTING_PROD_KEY }}
      run: |
        sudo npm i -g firebase-tools
        echo $SHAREZONE_PROD_KEY > sharezone-prod-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=sharezone-prod-key.json
        firebase deploy -m "Workflow $GITHUB_JOB, commit $GITHUB_SHA" --project prod
