name: ci_cd_tools
version: 0.0.1
publish_to: none

dependencies:
  args: "^1.5.2"
  path: "^1.6.4"
  http: "^0.12.1"
  async: "^2.4.1"
  yaml: "^2.2.1"
  quiver: any
  pub_semver: ^1.4.2
  colorize: ^2.0.0
  git: ^1.0.1
  pubspec_parse: "^0.1.5"
  test: ^1.14.7
  meta: ^1.1.8
  glob: ^1.2.0
  pedantic: ^1.9.0
  grinder: ^0.8.5
  union: ^0.0.3+1
  optional: ^4.1.0
  console: ^3.1.0
  rxdart: ^0.24.1

environment:
  sdk: ">=2.7.0 <3.0.0"
